name: Docs Build
on:
  push:
    branches:
    - develop
    paths:
    - 'arlunio/**'
    - 'docs/**'
    - '.github/workflows/docs-release.yml'
  pull_request:
    branches:
    - develop
    paths:
    - 'arlunio/**'
    - 'docs/**'
    - '.github/workflows/docs-release.yml'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Setup Environment
      run: |
        python --version

        python -m pip install --upgrade pip
        python -m pip install -e .[doc]
        python -m pip install -r docs/requirements.txt

    - name: Build Docs
      run: |
        cd docs
        make html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: develop
        BRANCH: gh-pages
        FOLDER: docs/_build/html
        TARGET_FOLDER: docs/
      if: github.event_name != 'pull_request'