name: CI

on:
  push:
    branches: 
    - develop
    - master
  pull_request:
    branches:
    - develop
    - master 

jobs:
  test:
    name: Test ${{ matrix.py_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-verison: ['3.6', '3.7', '3.8']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
        
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Check python version
      run: |
        python --version
